default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sql12722329
  username: sql12722329
  password: 4e82ELzUww
  host: sql12.freemysqlhosting.net
  port: 3306

test:
  <<: *default
  database: sas_2020_test


production:
  <<: *default
  database: sql12722329
  username: sql12722329
  password: 4e82ELzUww
  host: sql12.freemysqlhosting.net
  port: 3306

#email_list: 'imtiajromi@gmail.com,syedmustaquealiahamed@gmail.com,rajarshi903@gmail.com'

#bill_notification_email_list: "imtiajromi@gmail.com,sunshineadsolutions@gmail.com"

#bill_notification_email_list: 'imtiajromi@gmail.com,sunshineadsolutions@gmail.com'
